"""Stub file for appkit_mantine/markdown_preview.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Callable, Mapping, Sequence
from typing import Annotated, Any, Dict, Literal, Optional, Union
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import EventChain, EventHandler, EventSpec, EventType, FORM_SUBMIT_MAPPING, KeyInputInfo, PointerEventInfo
from reflex_base.style import Style
from reflex_base.vars.base import Var
import reflex
from typing import Any, ClassVar, Literal
import reflex as rx
from reflex.assets import asset
from reflex.components.component import ImportVar, NoSSRComponent
from appkit_mantine.base import MemoizedMantineProvider
MARKDOWN_PREVIEW_VERSION: str
REHYPE_SANITIZE_VERSION: str
REHYPE_REWRITE_VERSION: str
MERMAID_VERSION: str
KATEX_VERSION: str
_MARKDOWN_WRAPPER_ASSET = asset(path='markdown_preview_wrapper.js', shared=True)
_MARKDOWN_WRAPPER_IMPORT = _MARKDOWN_WRAPPER_ASSET.importable_path

class MarkdownPreview(NoSSRComponent):

    @classmethod
    def create(cls, *children, source: Var[str | None] | str | None=None, security_level: Literal['none', 'standard', 'strict'] | Var[Literal['none', 'standard', 'strict']] | None=None, enable_mermaid: Var[bool] | bool | None=None, enable_katex: Var[bool] | bool | None=None, prefix_cls: Var[str | None] | str | None=None, disable_copy: Var[bool | None] | bool | None=None, remark_plugins: Var[list[Any] | None] | list[Any] | None=None, rehype_plugins: Var[list[Any] | None] | list[Any] | None=None, rehype_rewrite: Any | Var[Any] | None=None, components: Var[dict[str, Any] | None] | dict[str, Any] | None=None, wrapper_element: Var[dict[str, Any] | None] | dict[str, Any] | None=None, style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None=None, key: Any | None=None, id: Any | None=None, ref: Var | None=None, class_name: Any | None=None, custom_attrs: dict[str, Any | Var] | None=None, on_blur: Optional[EventType[()]]=None, on_click: Optional[EventType[()] | EventType[PointerEventInfo]]=None, on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]]=None, on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]]=None, on_focus: Optional[EventType[()]]=None, on_mount: Optional[EventType[()]]=None, on_mouse_down: Optional[EventType[()]]=None, on_mouse_enter: Optional[EventType[()]]=None, on_mouse_leave: Optional[EventType[()]]=None, on_mouse_move: Optional[EventType[()]]=None, on_mouse_out: Optional[EventType[()]]=None, on_mouse_over: Optional[EventType[()]]=None, on_mouse_up: Optional[EventType[()]]=None, on_scroll: Optional[EventType[()]]=None, on_scroll_end: Optional[EventType[()]]=None, on_unmount: Optional[EventType[()]]=None, **props) -> 'MarkdownPreview':
        """Create the component.

Args:
    *children: The children of the component.
    source: no description
    security_level: no description
    enable_mermaid: no description
    enable_katex: no description
    prefix_cls: no description
    disable_copy: no description
    remark_plugins: no description
    rehype_plugins: no description
    rehype_rewrite: no description
    components: no description
    wrapper_element: no description
    style: The style of the component.
    key: A unique key for the component.
    id: The id for the component.
    ref: The Var to pass as the ref to the component.
    class_name: The class name for the component.
    custom_attrs: Attributes passed directly to the component.
    on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
    on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
    on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
    on_context_menu: Fired when the user right-clicks on an element.
    on_double_click: Fired when the user double-clicks on an element.
    on_mouse_down: Fired when the user presses a mouse button on an element.
    on_mouse_enter: Fired when the mouse pointer enters the element.
    on_mouse_leave: Fired when the mouse pointer leaves the element.
    on_mouse_move: Fired when the mouse pointer moves over the element.
    on_mouse_out: Fired when the mouse pointer moves out of the element.
    on_mouse_over: Fired when the mouse pointer moves onto the element.
    on_mouse_up: Fired when the user releases a mouse button on an element.
    on_scroll: Fired when the user scrolls the element.
    on_scroll_end: Fired when scrolling ends on the element.
    on_mount: Fired when the component is mounted to the page.
    on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
    **props: The props of the component.

Returns:
    The component."""
        ...
markdown_preview = MarkdownPreview.create
