profile: container

reflex:
  deploy_url: https://localhost
  frontend_port: 8080
  backend_port: 3030
  workers: 3
  default_timeout: 300  # seconds
  backend_timeout: 300  # seconds

app:
  environment: container
