profile: default

reflex:
  deploy_url: http://localhost
  frontend_port: 3000
  backend_port: 3031
  workers: 1

app:
  version: 0.5.0
  name: ManaKit App
  logging: logging.prod.yaml
  environment: prod
  backend_timeout: 180 # seconds

  database:
    username: secret:mn-db-user # pragma: allowlist secret
    password: secret:mn-db-password # pragma: allowlist secret
    host: secret:mn-db-host # pragma: allowlist secret
    port: 5432
    name: secret:mn-db-name # pragma: allowlist secret
    encryption_key: secret:mn-db-encryption-key # pragma: allowlist secret
    pool_size: 10 # change only when needed
    max_overflow: 30 # change only when needed
    echo: False # Set to True to enable SQL logging

  authentication:
    session_timeout: 25 # minutes
    auth_token_refresh_delta: 10 # minutes
    server_url: https://localhost
    server_port: 8080

    oauth_providers:
      - provider: "github"
        client_id: secret:mn-oauth-github-client-id # pragma: allowlist secret
        client_secret: secret:mn-oauth-github-client-secret # pragma: allowlist secret
        redirect_url: https://localhost:8080/oauth/github/callback

  assistant:
    perplexity_api_key: secret:mn-perplexity-api-key # pragma: allowlist secret
    openai_base_url: secret:mn-openai-api-endpoint
    openai_api_key: secret:mn-openai-api-key # pragma: allowlist secret

  imagegenerator:
    blackforestlabs_api_key: secret:mn-blackforestlabs-api-key # pragma allowlist secret
    google_api_key: secret:mn-google-api-key # pragma: allowlist secret
    openai_api_key: secret:mn-openai-api-key # pragma: allowlist secret
    openai_base_url: secret:mn-openai-api-endpoint # pragma: allowlist secret
    tmp_dir: ./uploaded_files
